/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 -T --shadows model.glb
Author: Karol Miklas (https://sketchfab.com/karolmiklas)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-1975-porsche-911-930-turbo-8568d9d14a994b9cae59499f0dbed21e
Title: FREE 1975 Porsche 911 (930) Turbo
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Car() {
  const { nodes, materials } = useGLTF('/models/car/model-transformed.glb')
  return (
    <group dispose={null} scale={0.5}>
      <mesh castShadow geometry={nodes.Object_4.geometry} material={materials['930_plastics']} position={[0, 0.38, 2.536]} rotation={[-2.834, 0, Math.PI]} scale={[0.812, 0.78, 0.812]} />
      <mesh castShadow geometry={nodes.Object_5.geometry} material={materials['930_stickers']} position={[0, 0.38, 2.536]} rotation={[-2.834, 0, Math.PI]} scale={[0.812, 0.78, 0.812]} />
      <mesh castShadow geometry={nodes.Object_6.geometry} material={materials.plate} position={[0, 0.38, 2.536]} rotation={[-2.834, 0, Math.PI]} scale={[0.812, 0.78, 0.812]} />
      <mesh castShadow geometry={nodes.Object_8.geometry} material={materials['930_rim']} position={[-0.944, 0.453, -0.982]} rotation={[0.479, 0, 0]} scale={0.812} />
      <mesh castShadow geometry={nodes.Object_9.geometry} material={materials['930_tire']} position={[-0.944, 0.453, -0.982]} rotation={[0.479, 0, 0]} scale={0.812} />
      <mesh castShadow geometry={nodes.Object_20.geometry} material={materials['930_lights']} position={[0.57, 0.418, -2.057]} rotation={[0.044, -0.215, 0.01]} scale={0.197} />
      <mesh castShadow geometry={nodes.Object_26.geometry} material={materials.glass} scale={0.812} />
      <mesh castShadow geometry={nodes.Object_28.geometry} material={materials['930_chromes']} scale={0.812} />
      <mesh castShadow geometry={nodes.Object_30.geometry} material={materials.paint} scale={0.812} />
      <mesh castShadow geometry={nodes.Object_32.geometry} material={materials.coat} scale={0.812} />
      <mesh castShadow geometry={nodes.Object_55.geometry} material={materials.black} position={[0.011, 1.355, 0.53]} scale={0.047} />
      <mesh castShadow geometry={nodes.Object_95.geometry} material={materials['930_lights_refraction']} scale={0.812} />
      <mesh castShadow geometry={nodes.Object_122.geometry} material={materials['930_wunderbaum']} position={[-0.002, 1.285, 0.542]} scale={0.812} />
      <mesh castShadow geometry={nodes.Object_140.geometry} material={materials.material_0} position={[0, 0.118, 0.225]} scale={[1.558, 1.558, 3.117]} />
    </group>
  )
}

useGLTF.preload('/models/car/model-transformed.glb')
